# Generated by Django 4.0.3 on 2022-04-13 21:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courtname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayof', models.DateField(default=datetime.date(2022, 4, 13))),
                ('starttime', models.TimeField(default='14:30')),
                ('endtime', models.TimeField(default='14:30')),
                ('court', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='court', to='rexsite.courts')),
            ],
        ),
    ]
