# Generated by Django 4.0.3 on 2022-04-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rexsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='firstname',
            field=models.CharField(default='john', max_length=40),
        ),
        migrations.AddField(
            model_name='reservation',
            name='lastname',
            field=models.CharField(default='doe', max_length=40),
        ),
    ]
