# Generated by Django 4.0.3 on 2022-04-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rexsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courtname', models.CharField(max_length=30)),
            ],
        ),
    ]
