# Generated by Django 4.0.3 on 2022-04-12 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rexsite', '0003_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='day',
            field=models.DateField(default=datetime.date(2022, 4, 12)),
        ),
    ]
